apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mysql-namespace.yaml
  - mysql-secret.yml
  - mysql-storage.yml  
  - mysql-service.yml
  - mysql-cfgmap.yml
  - mysql-deployment.yml